-- First Light Quote Tool — Contract generation feature: schema changes
-- Run in the Supabase SQL editor: SANDBOX first (prove), then LIVE.
-- Idempotent — safe to re-run. Run this BEFORE re-running rls-policies.sql.

-- 1. Snapshot of the generated contract, stored on the quote
--    (payment schedule, total, terms version, contract date…). Nullable; normal saves ignore it.
alter table public.quotes add column if not exists contract_meta jsonb;

-- 2. company_settings — holds the BANK DETAILS so they NEVER live in the public index.html.
--    The deployed static file is public (the login gate is client-side), so anything hardcoded
--    there is readable by anyone. Keeping bank details here, behind RLS+Auth, is the only way to
--    keep them off the public surface. One row.
create table if not exists public.company_settings (
  id             bigint generated by default as identity primary key,
  bank_name      text,
  account_number text,
  sort_code      text,
  updated_at     timestamptz default now()
);

-- 3. RLS: authenticated-only, anon fully denied (same model as the other tables).
alter table public.company_settings enable row level security;
do $$
declare p record;
begin
  for p in select policyname from pg_policies where schemaname='public' and tablename='company_settings'
  loop execute format('drop policy %I on public.company_settings', p.policyname); end loop;
end $$;
create policy fl_authenticated_all on public.company_settings
  for all to authenticated using (true) with check (true);

-- 4. SEED THE BANK ROW — ⚠ DO NOT COMMIT REAL VALUES TO ANY FILE. Type them here, in the dashboard.
--    Run ONE of the following once (uncomment + fill in the real details by hand):
--
--    -- first time (no row yet):
--    insert into public.company_settings (bank_name, account_number, sort_code)
--    values ('FirstLight Landscaping Ltd', '<ACCOUNT_NUMBER>', '<SORT-CODE>');
--
--    -- if a row already exists:
--    update public.company_settings
--       set bank_name='FirstLight Landscaping Ltd', account_number='<ACCOUNT_NUMBER>',
--           sort_code='<SORT-CODE>', updated_at=now();

-- 5. Verify (run while logged in to the dashboard):
--    select rowsecurity from pg_tables where tablename='company_settings';   -- expect true
--    select * from public.company_settings;
--    -- Anon probe (with the publishable key, no login) must return [] — prove anon is denied.

-- 6. Editable contract terms (2026-06-26): the Contract-of-Works terms move from hardcoded JS into
--    this row, edited in-app via the Price Manager "Contract Terms" card. Additive + nullable; the
--    app falls back to its built-in CONTRACT_TERMS until the first in-app Save writes this column.
alter table public.company_settings add column if not exists contract_terms jsonb;
--    verify: select id, contract_terms from public.company_settings;   -- null until first in-app save
