-- E-signature feature: contract_signing table (signing build, Phase 1 - 2026-07-24)
-- One row = one contract sent for signature. The row is the LEGAL RECORD:
-- it freezes the contract HTML (countersigned) + a SHA-256 hash at send time,
-- and accumulates the evidence trail (viewed/signed timestamps, IP, user agent,
-- drawn + typed signatures) as the client acts.
--
-- Design decisions (Neal, 2026-07-24):
--   * 1 or 2 signers per contract (joint homeowners); signed = ALL signers signed.
--   * Per-signer secret link tokens (better evidence of who opened what).
--   * 30-day link expiry (expires_at; revocable/re-sendable any time).
--   * Client must draw a signature AND type their name AND tick agreement.
--   * Signing never changes quote status (contracts only exist once Accepted).
--   * NO foreign key to quotes - deliberate: the legal record must survive
--     even if the quote is later deleted or renumbered.
--
-- The client's browser NEVER touches this table: no anon policy (RLS denies),
-- and the sign-contract edge function (Phase 4) uses the service role.
-- Run on SANDBOX first; live only at the Phase 8 cutover.

create table if not exists contract_signing (
  id            bigint generated by default as identity primary key,
  quote_ref     text not null,
  customer      text,                        -- denormalised so the record is self-contained
  status        text not null default 'sent',-- sent | viewed | signed | revoked (expired is derived from expires_at)
  contract_html text not null,               -- frozen countersigned contract, verbatim
  contract_hash text not null,               -- SHA-256 hex of contract_html at send time
  terms_version integer,                     -- from contract_meta, provenance only
  signers       jsonb not null,              -- [{token, name, email, viewed_at, signed_at, typed_name, signature_image, ip, user_agent}]
  sent_at       timestamptz not null default now(),
  expires_at    timestamptz,                 -- sent_at + 30 days (app sets it; extendable)
  signed_at     timestamptz,                 -- stamped when the LAST signer signs
  revoked_at    timestamptz,
  created_by    text,                        -- staff email that sent it
  meta          jsonb                        -- future-proofing (resend history, notes)
);

create index if not exists contract_signing_quote_ref_idx on contract_signing (quote_ref);
-- token lookup by the edge function: containment query into the signers array
create index if not exists contract_signing_signers_gin on contract_signing using gin (signers jsonb_path_ops);

-- RLS: staff (authenticated) full access, anon denied - same convention as every table
alter table contract_signing enable row level security;
drop policy if exists fl_authenticated_all on contract_signing;
create policy fl_authenticated_all on contract_signing
  for all to authenticated using (true) with check (true);

-- §2 (Phase 2): company countersignature — {name, role, image (data URL), updatedAt, updatedBy}
-- Same storage pattern as contract_terms/note_templates: jsonb on company_settings,
-- existing RLS covers it. Captured once in the Price Manager "Company Signature" card;
-- stamped into every contract frozen for e-signature at send time.
alter table company_settings add column if not exists company_signature jsonb;

-- PostgREST schema-cache gotcha: without this, the API 400s (PGRST204) on the new table
NOTIFY pgrst, 'reload schema';

select 'contract_signing ready' as status;
