-- Design contracts feature (design build D1 - 2026-07-28). SANDBOX FIRST; live at the
-- combined Phase 8 cutover. Replaces Xero-issued design contracts so HelloSign + the
-- Xero step can both be dropped.
--
-- Design decisions (Neal): DC-0001 numbering (fresh series, no continuation of Xero's
-- FL numbers); packages in their OWN table (never mixed into deliverables/quote
-- pickers/Order List); design contracts NOT in Saved Quotes; no designer field
-- (deliberately dropped - only total sales data matters); terms live in
-- company_settings.design_terms (same pattern as contract_terms, seeded by the first
-- in-app save of the verbatim transcription from the signed FL-3456/FL-3466 PDFs).

-- ── packages catalogue ──────────────────────────────────────────────────────────
create table if not exists design_packages (
  id           bigint generated by default as identity primary key,
  code         text not null unique,          -- GD01, GD02, GD03, SRV01...
  name         text not null,
  description  text,                          -- client-facing, auto-fills the contract line
  default_fee  numeric,                       -- ex VAT; editable per contract
  sort_order   numeric,
  is_archived  boolean default false
);

-- ── design contracts ────────────────────────────────────────────────────────────
-- ref is the PK (DC-0001), mirroring quotes.ref. lines: [{code, name, description,
-- qty, fee, vat}]. contract_meta: same freeze-snapshot shape as quotes.contract_meta
-- (generatedAt, contractDate, schedule/freeText, terms snapshot + numbering style,
-- snapshot for exact re-render) so the whole contract engine is reused unchanged.
create table if not exists design_contracts (
  ref           text primary key,
  customer      text,
  addr1         text,
  city          text,
  post          text,
  date          text,
  lines         jsonb,
  contract_meta jsonb,
  created_by    text,
  saved         timestamptz default now()
);

-- ── numbering (mirrors qt_counter / next_qt_number) ────────────────────────────
create table if not exists dc_counter (id bigint primary key, last_number integer);
insert into dc_counter (id, last_number) values (1, 0) on conflict (id) do nothing;

CREATE OR REPLACE FUNCTION public.next_dc_number()
 RETURNS integer
 LANGUAGE plpgsql
AS $function$DECLARE next_val integer;
BEGIN
  UPDATE dc_counter SET last_number = last_number + 1
  WHERE id = 1
  RETURNING last_number INTO next_val;
  RETURN next_val;
END;$function$;
revoke execute on function next_dc_number() from public, anon;
grant execute on function next_dc_number() to authenticated;

-- ── design terms alongside the build terms ─────────────────────────────────────
alter table company_settings add column if not exists design_terms jsonb;

-- ── RLS: staff-only, anon denied (fl convention) ───────────────────────────────
alter table design_packages enable row level security;
drop policy if exists fl_authenticated_all on design_packages;
create policy fl_authenticated_all on design_packages
  for all to authenticated using (true) with check (true);

alter table design_contracts enable row level security;
drop policy if exists fl_authenticated_all on design_contracts;
create policy fl_authenticated_all on design_contracts
  for all to authenticated using (true) with check (true);

alter table dc_counter enable row level security;
drop policy if exists fl_authenticated_all on dc_counter;
create policy fl_authenticated_all on dc_counter
  for all to authenticated using (true) with check (true);

-- ── seed packages (fees editable in-app; GD03 + SRV01 fees TBC by Neal) ────────
insert into design_packages (code, name, description, default_fee, sort_order) values
('GD01', 'Garden Design Service — Standard Package',
'FirstLight Landscaping''s Standard Package Includes:
- 1 Garden design option
- 2D Plan with dimensions, and a descriptive key for each element included in the design
- A mood board capturing the overall aesthetic, which may include suggested materials, planting and structural elements.

FirstLight Landscaping''s standard package garden design service includes:

- An initial meeting with the designer to establish the design brief and carry out the on-site survey.
- A second meeting where the designer will present one tailored garden design concept. This will be delivered as a printed plan that aligns with the established design brief.
- Up to two sets of amendments to your design concept to develop the scheme
- A completed design print out containing the finalised garden design. This includes a scaled rendered plan, and a mood board of suggested materials, planting and structural elements.
- A full broken-down quotation for all work in the design', 1250, 10),
('GD02', 'Garden Design Service — Standard Plus Package',
'FirstLight Landscaping''s Standard Plus Package Includes:
- 1 Garden design option
- 2D Plan with dimensions, and a descriptive key for each element included in the design
- A mood board capturing the overall aesthetic, which may include suggested materials, planting and structural elements.
- 3D Visuals
- 3D Fly-through of the design

FirstLight Landscaping''s standard plus package garden design service includes:

- An initial meeting with the designer to establish the design brief and carry out the on-site survey.
- A second meeting where the designer will present one tailored garden design concept. This will be delivered as a printed booklet that includes one to-scale plan that aligns with the established design brief, a mood board, and a set of 3D visuals taken from various points of the garden.
- Up to two sets of amendments to your design concept to develop the scheme.
- A completed printed design booklet containing the finalised garden design. This includes a scaled general arrangement plan, a rendered plan, a mood board of suggested materials, planting and structural elements, as well as 3D visuals of the final design.
- A full broken-down quotation for all work in the design', 1650, 20),
('GD03', 'Garden Design Service — Premium Package',
'FirstLight Landscaping''s Premium Package Includes:
- 2 Garden design options
- 2D Plan for each option with dimensions, and a descriptive key for each element included in the design
- A mood board for each option, capturing the overall aesthetic, which may include suggested materials, planting and structural elements
- 3D Visuals for each option
- 3D Fly-through for each option

FirstLight Landscaping''s premium package garden design service includes:

- An initial meeting with the designer to establish the design brief and carry out the on-site survey.
- A second meeting where the designer will present two tailored garden design concepts. This will be delivered as a printed booklet that includes two to-scale plans that aligns with the established design brief, a mood board for each option, and a set of 3D visuals for each option taken from various points of the garden.
- Up to two sets of amendments to your preferred design concept to develop the scheme.
- A completed printed design booklet containing the finalised garden design. This includes a scaled general arrangement plan, a rendered plan, a mood board of suggested materials, planting and structural elements, as well 3D visuals of the final design.
- A full broken-down quotation for all work in the design', 0, 30),
('SRV01', 'Topographical Survey',
'A topographical survey of the site, carried out on our behalf by a third-party surveyor commissioned by FirstLight Landscaping. The survey fee is payable on completion of the survey.', 0, 40)
on conflict (code) do nothing;

NOTIFY pgrst, 'reload schema';
select 'design contracts schema ready' as status;
