-- ============================================================================
-- RAMS feature (Risk Assessment & Method Statement) — schema
-- Run on SANDBOX first (erbrflbialsyxbjawopy); LIVE only at cutover.
-- Patterns follow contract-signing.sql:
--   * NO foreign key to quotes — a signed RAMS is a legal record and must
--     survive quote deletion.
--   * expired is DERIVED from expires_at, never stored.
--   * per-SIGNER tokens live inside the signers jsonb array; the edge function
--     looks rows up by token containment, hence the GIN jsonb_path_ops index.
-- After running: NOTIFY pgrst, 'reload schema';  (PostgREST schema-cache gotcha)
-- ============================================================================

-- §1  Library storage — single-row company_settings pattern (same as
--     contract_terms / note_templates), so existing RLS covers it.
--     Shape: { version, updatedAt, updatedBy,
--              core:      [{id:'A1',  title, html}],
--              modifiers: [{id:'B1',  title, html, defaultOn:true}],
--              modules:   [{id:'C1',  title, html}],
--              mapping:   [{category, modules:[ids], nameMatch?}],   -- editable; remap after catalogue rebuild
--              ppe:       {title, html},
--              docText:   {opening, declaration, revisionRule, workingHours} }
alter table company_settings add column if not exists rams_library jsonb;

-- §2  Per-job RAMS documents. One row per issued generation; a revision
--     creates a NEW row and marks the old one superseded (superseded_by).
create table if not exists rams_docs (
  id           bigint generated by default as identity primary key,
  quote_ref    text not null,
  customer     text,
  revision     int not null default 1,
  status       text not null default 'draft',   -- draft | approved | issued | signed | superseded
  review       jsonb,        -- {modules:[ids], modifiers:[ids], extraNotes, nearestAE, workingHours, emergencyContacts, siteAddress}
  doc_html     text,         -- frozen standalone document, set at ISSUE (never mutated after)
  doc_hash     text,         -- SHA-256 of doc_html
  signers      jsonb not null default '[]'::jsonb,
    -- [{name, token, viewed_at, signed_at, signature_image, typed_name, name_adopted, ip, user_agent}]
  approved_by  text,
  approved_at  timestamptz,
  issued_at    timestamptz,
  expires_at   timestamptz,  -- issued_at + 90 days (app sets; re-issue extends; signed signers keep read access)
  signed_at    timestamptz,  -- set when ALL signers have signed
  superseded_by bigint,      -- id of the revision row that replaced this one
  created_at   timestamptz not null default now()
);

create index if not exists rams_docs_ref_idx     on rams_docs (quote_ref);
create index if not exists rams_docs_signers_gin on rams_docs using gin (signers jsonb_path_ops);

-- §3  RLS — authenticated-only, matching every other table (rls-policies.sql pattern).
alter table rams_docs enable row level security;
drop policy if exists fl_authenticated_all on rams_docs;
create policy fl_authenticated_all on rams_docs
  for all to authenticated using (true) with check (true);

-- ============================================================================
-- Rollback (dashboard emergencies only):
--   drop table if exists rams_docs;
--   alter table company_settings drop column if exists rams_library;
-- ============================================================================
